using UnityEngine;

public class ModalMessages : MonoBehaviour
{
    private string[] headers0 =
    {
        "Hotel Bristol",
        "Dom bez Kantów",
        "Neon",
        "Serce Chopina",
        "Autobus",
        "Pastorał Warszawski",
        "Kamienica Księży Misjonarzy",
        "Rowerzysta",
        "Pracownik MPO",
        "Straż Miejska",
        "Bankomat",
        "Kiosk „Ruch”"
    };

    private string[] messages0 =
    {
        "Hotel Bristol, otwarty 19 listopada 1901 roku, został wybudowany na miejscu pałacu Tarczyńskich. Jednym z  inicjatorów jego budowy był Ignacy Jan Paderewski.",
        "„Dom bez kantów” z mieszkaniami dla oficerów i żonatych podoficerów zawodowych stanął na miejscu tzw. kuźni saskich – stajni, kuźni i budynku z kwaterami oficerskimi. Wybudowany  w latach 1933-1935 przez Ministerstwo Spraw Wojskowych.",
        "Pierwszy neon w Warszawie rozbłysnął w 1926 roku – była to reklama browaru „Haberbusch i Schiele” na dachu willi Marconiego przy skrzyżowaniu Marszałkowskiej i Alej Jerozolimskich. Choć neon przedstawiał  butelkę z napisem „Porter”, warszawiacy nazywali go neonem „Philipsa”.",
        "Fortepian Fryderyka Chopina stał w mieszkaniu jego siostry, Izabeli Barcińskiej w pałacu Zamoyskich do 19 września 1963 roku. Tego dnia został wyrzucony przez okno na ulicę przez rosyjskich żołnierzy w ramach działań odwetowych podczas trwającego powstania styczniowego. Kilkanaście  lat wcześniej urna z sercem Fryderyka Chopina trafiła do Warszawy. W 1880 roku urnę z sercem kompozytora umieszczono w filarze kościoła Św. Krzyża.",
        "Pierwsze autobusy pojawiły się w Warszawie w roku 1920. Były to pojazdy szwajcarskiej marki Saurer. Przed wybuchem II wojny światowej po Warszawie jeździło 180 autobusów.",
        "Latarnia elektryczna typu „pastorał warszawski” miała kilka wzorów wprowadzanych kolejno w latach – 1904, 1907, 1923 i 1928. Wprawdzie pierwsze latarnie elektryczne  pojawiły się w Warszawie już w 1878 roku, lecz były to lampy łukowe stawiane jedynie czasowo m.in. w Ogrodzie Saskim. Dopiero od roku 1904 rozpoczęto iluminację ulic Warszawy za pomocą „pastorałów”.",
        "W kamienicy Księży Misjonarzy na Krakowskim Przedmieściu 1.  Jan Karski, w 1939 roku, rozpoczął tu swoją działalność konspiracyjną. To dzięki niemu świat dowiedział się o zbrodni Holocaustu. Później  w kamienicy mieściła się komenda policji.",
        "Pierwsze  sprowadzone z Anglii bicykle „z gumowymi obręczami” pojawiły się w Warszawie około 1872 roku. Dwadzieścia lat później poniżej skarpy wiślanej na Dynasach, sąsiadujących z Krakowskim Przedmieściem, zbudowano pierwszy tor kolarski.",
        "Śmieci, określane jako nieczystości stałe, wywożone były w XVIII-wiecznej Warszawie na wozach dwukołowych nazywanych karami. Zjeżdżały one w stronę Wisły ulicą sąsiadującą z Kościołem Wizytek. Od roku 1770  ulica ta nosi nazwę Karowej od karów – nazwy tych osiemnastowiecznych śmieciarek.",
        "Policja municypalna powstała w Warszawie w 1817 roku i dzieliła się na  policję śledczą, sądowo-policyjną, urząd targowo-tandetny oraz służbę rogatkową. W 1991 roku została utworzona Straż Miejska nadzorowana przez samorząd i niepodlegająca policji.",
        "Pierwszy bankomat w historii został uruchomiony w 1967 w Londynie. Wzorowany był na urządzeniach sprzedających słodycze. Pierwszy bankomat w Polsce pojawił się 20 lat później, w 1987 roku w III oddziale Banku PKO w Warszawie.",
        "Pierwszy kiosk „Ruchu” otwarto 1919 na dawnym dworcu kolei warszawsko-wiedeńskiej;"
    };

    private string[] exHeaders0 =
    {
        "Kościół św. Krzyża",
        "Kamienica Księży Misjonarzy",
        "Targ",
        "Brama Szkoły Rycerskiej",
        "Pałac Tyszkiewiczów (nazywany także pałacem Tyszkiewiczów-Potockich)",
        "Pałac Lubomirskich",
        "Pałac Radziwiłłów",
        "Kościół Karmelitów (w budowie)",
        "Ratusz jurydyki Dziekanii",
        "Karety (dwukonne)",
        "Drążnik miejski (ówczesny strażnik)",
        "Zakonnicy",
        "Księża",
        "Para z wyższych sfer",
        "Szlachcice",
        "Zamożny chłop"
    };

    private string[] exMessages0 =
    {
        "Pierwszy, drewniany kościół Św. Krzyża stanął w roku 1525. W roku 1653 został przekazany Zgromadzeniu Księży Misjonarzy. Podczas potopu szwedzkiego, cztery lata później, najeźdźcy splądrowali i spalili świątynię. Jej odbudowa w stylu barokowym zajęła 16 lat (od 1679 do 1696 roku), a była realizowana według projektu nadwornego architekta królewskiego, pochodzącego z Włoch, Józefa Szymona Bellottiego. Kościół, wówczas największa budowla sakralna w mieście, był stale rozbudowywany. Najpierw, w latach 1726-1754, wzniesiono dwie wieże, którym kształt nadał Antoni Fontana. Potem w roku 1756 na prawej wieży umieszczono zegar oraz cztery dzwony. W tym samym czasie zakończyły się prace nad fasadą kościoła zdobioną rzeźbami. Pracami tymi kierował syn Antoniego Fontany – Jakub. Do gmachu od frontu prowadził z dwóch stron wybrukowany podjazd, którym uprzywilejowani wierni, zajeżdżali swymi powozami pod same drzwi. W dni powszednie dostęp do niego był odcięty łańcuchem. Przed podjazdem znajdowały się łukowo wygięte schody. Ich balustrady wieńczyły posągi czterech ewangelistów i zdobiły kamienne wazony. W roku 1818 podjazd został zlikwidowany, natomiast schody przesunięto bliżej fasady budynku. W drugiej połowie XVIII wieku kościół zyskał rangę drugiej najważniejszej świątyni w mieście – po kolegiacie św. Jana. Miały tu swoje miejsce uroczystości państwowe, w tym - od 1765 roku - nabożeństwa połączone z ceremonią nadawania przez króla Stanisława Augusta Orderu św. Stanisława. W 1792 roku, w pierwszą rocznice uchwalenia Konstytucji 3 Maja, odbyła się tu msza z udziałem króla, senatorów, posłów i ambasadorów, po której ruszyła procesja zakończona poświęceniem kamienia węgielnego pod budowę świątyni Opatrzności Bożej - w miejscu dzisiejszego Ogrody Botanicznego. W XIX wieku świątynia zaczęła pełnić funkcję mauzoleum zasłużonych dla ojczyzny. Znajdują się tu liczne nagrobki lub epitafia poświęcone m.in. Stanisławowi Małachowskiemu, Juliuszowi Słowackiemu, Zygmuntowi Krasińskiemu, Bolesławowi Prusowi i Władysławowi Sikorskiemu. W filarze świątyni po lewej stronie zostały wmurowane urny z sercami Fryderyka Chopina i Władysława Reymonta. Odbywały się tu manifestacje patriotyczne i pogrzeby wielkich Polaków: Józefa Poniatowskiego, Stanisława Staszica, Stanisława Moniuszko, Karola Szymanowskiego. O świątynię toczyły się ciężkie walki podczas insurekcji kościuszkowskiej, a potem powstania warszawskiego. To właśnie od tego kościoła wzięła swoją nazwę biegnąca nieopodal ulica Świętokrzyska.",
        "Zgromadzenie Księży Misjonarzy zostało sprowadzone do Polski z Francji przez Ludwikę Marię Gonzagę, żonę króla Jana Kazimierza. Należąca do nich kamienica, usytuowana po lewej stronie kościoła Św. Krzyża, została wybudowana przed 1740 rokiem jako jednopiętrowy, murowany dom z mansardowym, łamanym dachem i asymetryczną facjatką nakrytą trójkątnym przyczółkiem. W połowie XIX wieku gmach został znacznie rozbudowany. W 1864 roku budynek został Księżom Misjonarzom odebrany. W okresie międzywojennym i podczas okupacji mieściła się tu komenda policji. ",
        "Naprzeciw kościoła Św. Krzyża znajdował się targ, na którym z lichych kramów, straganów  i koszy sprzedawano przede wszystkim żywność: warzywa, owoce, ryby, mięso, kiełbasy oraz gorące potrawy. Zazwyczaj targowano tu nielegalnie. Jedynie raz do roku - 3 maja - targ miał charakter oficjalny, bowiem był dniem tzw. odpustu. Kościół Św. Krzyża obchodził wówczas święto na pamiątkę odnalezienia przez św. Helenę (matkę cesarza  Konstantyna) Krzyża Świętego, co miało miejsce 3 maja 326 roku w Jerozolimie.",
        "Brama zaprojektowana przez Jana Zygmunta Deybla i Joachima Daniela Jaucha, którą około 1732 polecił zbudować August II Mocny. Była ona zwieńczona charakterystycznym wielkim blaszanym globem.  W roku malowania obrazu (1778) brama prowadziła do założonej przez króla, Stanisława Augusta Poniatowskiego, Szkoły Rycerskiej. Powstała ona w roku 1765. Jej zadaniem było  przygotowywanie młodzieży do służby wojskowej i cywilnych zadań publicznych. Idea przyświecająca jej powstaniu to „edukacja społeczeństwa poprzez edukację jednostki”. W 1816 na terenach Szkoły Rycerskiej, powołany został na mocy dekretu imperatora Aleksandra I - Królewski Uniwersytet Warszawski. W roku 1823 bramę Augusta Mocnego zastąpiła skromniejsza brama, położona nie na linii ulicy lecz bardziej cofnięta w głąb terenu uniwersyteckiego.",
        "Został zbudowany w latach 1785-1792  dla hetmana polnego litewskiego, Ludwika Tyszkiewicza, ożenionego z Konstancją Poniatowską, bratanicą króla Stanisława Augusta. Budowę pałacu rozpoczęto w 1785, według projektu Stanisława Zawadzkiego i Jana Chrystiana Kamsetzera. W 1840 roku pałac przeszedł w ręce rodziny Potockich. W 1923 roku zakupił go Bank Gospodarstwa Krajowego, po czym ulokowano tu Polską Akademię Literatury oraz zbiory starodruków Biblioteki Narodowej. W czasie powstania warszawskiego budynek został celowo zbombardowany przez wojska niemieckie pociskami zapalającymi, aby zniszczyć nie tylko gmach, ale i zbiory. Pałac jest klasycystyczną budowlą z dwiema elewacjami od strony Krakowskiego Przedmieścia oraz placyku przy kościele Wizytek. Należy do typu pierzejowego (przyulicznego). Oznacza to, że został wzniesiony w linii zabudowy ulicy i nie poprzedza go dziedziniec ujęty bocznymi skrzydłami, jak w większości XVIII-wiecznych warszawskich pałaców. Elewację od strony Krakowskiego Przedmieścia zdobi charakterystyczny balkon podtrzymywany przez cztery figury Atlasów. W budynku mieści się dziś Muzeum Uniwersytetu Warszawskiego. Jako ciekawostkę warto wiedzieć, że projekt pałacu nie przewidywał budowy sali balowej, co związane było z brakiem upodobania fundatora, Ludwika Tyszkiewicza, do hucznych i głośnych rozrywek. W miejsce sali balowej powstała natomiast obszerna bawialnia.",
        "Pałac został wzniesiony dla starosty tczewskiego Franciszka Andraulta w roku 1655. Później przeszedł w ręce księcia Kazimierza Czartoryskiego, zaś od 1758 roku stanowił własność Stanisława Lubomirskiego, następnie Ignacego Potockiego i ostatecznie od 1802 własność Tarnowskich. Był kilkakrotnie przebudowywany. Po rozbiórce w 1898 roku na jego miejscu stanął Hotel Bristol.",
        "Budowę korpusu głównego w miejscu znajdującego się tu wcześniej dworu rozpoczął ok. 1643 roku hetman wielki koronny Stanisław Koniecpolski. Pierwotnie był to barokowy pałac z obszernym ogrodem typu włoskiego, schodzącym aż do Wisły, płynącej wówczas znacznie bliżej skarpy.  Budynek był kilkakrotnie przebudowywany. W połowie XVIII wieku od strony ulicy wzniesiono skrzydła boczne okalające rozległy dziedziniec. Po Koniecpolskich pałac stanowił własność Lubomirskich i Radziwiłłów. Odbywały się tu liczne uczty i bale. Jednym z najbardziej znanych jego mieszkańców był książę Karol Radziwiłł zwany Panie Kochanku, najzamożniejszy polski magnat drugiej połowy XVIII wieku i jeden z najbogatszych ludzi ówczesnej Europy. Wojewoda wileński, nazywany również „niedźwiedziem litewskim”, znany był z ekstrawaganckich pomysłów. Pewnego razu zajechał na Zamek Królewski w odwiedziny do Stanisława Augusta karetą zaprzężoną w cztery niedźwiedzie wzbudzając powszechną panikę.  Poróżniony z Czartoryskimi i królem przestał bywać w stolicy, a pałac zaczęto wynajmować, co przynosiło spory dochód. W  latach 1773-1818 z przerwami był wynajmowany na cele teatralne. W 1778 roku odbyła się tu premiera polskiej opery Nędza uszczęśliwiona, a w latach 1804–1806 występował  zespół Wojciecha Bogusławskiego.  W styczniu 1807 roku na przedstawieniu sztuki Andromeda gościł tu Napoleon Bonaparte, a w 1815  zatrzymał się w nim car Aleksander I. 24 lutego 1818",
        "Kościół w stylu barokowym zbudowano w latach 1661–1681 dla karmelitów bosych, prawdopodobnie według projektu Constantego Tencalli. Postawiony został na planie krzyża z jednoprzestrzenną nawą i głębokimi kaplicami po bokach, które sprawiają wrażenie naw bocznych. W latach 1762–1780 fasada gmachu została przebudowana według projektu Efraima Schroegera w stylu wczesnego klasycyzmu francuskiego. Wykonano ją z kamienia, co jest w Warszawie rozwiązaniem unikatowym. W chwili, kiedy Canaletto malował swój obraz, trwał ostatni etap prac budowlanych, o czym świadczy wysokość rusztowań przy fasadzie kościoła.",
        "Jurydyki były prywatnymi  terenami  w obrębie miasta lub na gruntach podmiejskich, wydzielonymi spod działania sądownictwa i administracji miejskiej. Ich właścicielami była szlachta, magnateria lub Kościół. Jurydyki istniały już w XV wieku, ale ich rozkwit  nastąpił między XVI a XVII wiekiem, po uzyskaniu pełnej dominacji szlachty nad miastami. W miejscach takich powstawały struktury konkurencyjne wobec ich miejskich odpowiedników, nieskrępowane przepisami i ograniczeniami miejskimi — odbywały się w nich targi i jarmarki, działali niezrzeszeni w cechach rzemieślnicy (partacze). W przypadku Warszawy jurydyki powstawały wokół Starego i Nowego Miasta, ograniczając tym samym możliwości ich rozwoju. Niektóre z nich tworzyły małe miasteczka, inne zajmowały jedną ulicę lub kilka posesji.  Posiadały swoich rajców, burmistrza i sąd. W Warszawie XVIII wieku było ich ponad 20 (m.in. Leszno, Nowy Świat, Mariensztat, Solec, Grzybów).  Zostały zlikwidowane przez Konstytucję 3 Maja w 1791 roku. Do najstarszych i najmniejszych jurydyk Warszawy zaliczał się Dziekanka należąca do kapituły warszawskiej. Była położona po obu stronach Krakowskiego Przedmieścia w okolicach dzisiejszego skweru z pomnikiem Adama Mickiewicza, gdzie stał ratusz. ",
        "Bogato zdobiony czterokołowy pojazd zaprzęgowy w kształcie prostopadłościanu, żartobliwie zwany „arką”. Rozpowszechnił się wśród polskich wyższych warstw społecznych w XVII wieku. Karety dwukonne były zazwyczaj dwuosobowe. Obie karety na obrazie Canaletta różnią się nie tylko indywidualnymi zdobieniami, ale także różnymi kolorami i krojami liberii (strojów) obsługującej je służby. W owym czasie liberie służby pozwalały określić status pasażera (właściciela) pojazdu. Na pierwszym planie widać karetę z jednym lokajem, stojącym z tyłu pojazdu, co sugerować może, że znajduje się w nim jeden pasażer. W karecie na dalszym planie widać dwóch lokajów, co z kolei wskazuje, że prawdopodobnie przewozi więcej osób. ",
        "Drążnik na głowie ma kołpak, ubrany jest w płaszcz z guzikami (z wytłoczonymi prawdopodobnie symbolami jurydyki. Drążnik uzbrojony został w solidny drewniany kij, którym mógł egzekwować prawo. Jako strażnik dbał o porządek na placach targowych oraz chronił zabudowania przed ogniem. ",
        "Prawdopodobnie są to księża ze zgromadzenia Misjonarzy, do których należał pobliski kościół Św. Krzyża. Świadczą o tym długie płaszcze zakonne oraz fakt, że jeden z nich ma widoczny, wyłożony, biały kołnierzyk, co było charakterystycznym elementem stroju właśnie Księży Misjonarzy.",
        "Dwaj księża w sutannach noszą na głowach popularne w XVIII wieku wśród kleru świeckiego tak zwane „rzymskie kapelusze”  nazywane też saturno. Włosi określali je mianem cappello romano  (pl. - cappelli romani).",
        "Przedstawiona przez Canaletta para należy do warstw wyższych, o czym świadczy jej strój odwołujący się do mody francuskiej.  Mężczyzna ma na głowie perukę okrytą tricornem (trójkątnym kapeluszem).  Nosi też habit à la française - wytworny wierzchni ubiór męski bogato zdobiony przy brzegach haftem, często o motywach kwiatowych. Ma też widoczne na nogach pończochy, ponieważ nosi spodnie do kolan czyli tzw.  culotte. Stojąca obok niego dama ma dwie spódnice: spodnią (białą prawdopodobnie z aksamitu)  i wierzchnią (czerwoną) - przy czym ta druga wykonana jest z bardziej kosztownego materiału. Wzrok przyciąga granatowe karako (od francuskiego „caraco”) czyli krótki, dopasowany żakiecik z szerokim zaokrąglonym kołnierzem i mocno zmarszczoną z tyłu baskinką. Jej głowę ozdabia fryzura w stylu „sułtańskim” przysłonięta chustą z trójkolorowej gazy.",
        "Dwóch szlachciców ma na głowach czapki rogatywki nazywane też konfederatkami.  Rozpowszechniły się one w Polsce jako nakrycie głowy patriotycznego ruchu konfederatów barskich w 1768 roku, stąd ich nazwa. Konfederatki były sukiennymi czapkami bez daszka, o główce z kwadratowym denkiem, koloru zwykle karmazynowego, obszyte barankiem: czarnym lub siwym. Przy lewym boku przypinano do niej często kokardę, rozetę lub krzyż kawalerski i pióra lub kitę. Wierzchnie odzienie szlachciców stanowią kontusze, pod spodem widać żupany. Obaj przewiązani są zdobnymi pasami, do których przypięte są karabele (szable). Na nogach mają charakterystyczne buty zwane baczmagami. Noszenie przez szlachtę konfederatek oznaczało ich nieprzychylny stosunek do króla Stanisława Augusta.",
        "Włościanin ma na głowie prosty kołpak. Odzienie wierzchnie stanowi kazakin czyli krótki kaftan, noszony początkowo przez Kozaków, odzienie spodnie stanowi długa koszula do kolan oraz buty z cholewami.",
    };

    private string[] headers1 = 
    {
        "header1",
    };

    private string[] messages1 = 
    { 
        "message1",
    };

    private string[] exHeaders1 = 
    {
        "Kościół Wizytek",
        "Dworek przy kościele",
        "Pnie drzew",
        "Drewniane budynki.",
        "Targ Sienny",
        "Kareta jednoosobowa",
        "Mieszczanin z żoną ubrany w strój polski.",
        "Szlachcic na koniu ubrany w strój  francuski",
        "Tragarz z workiem obroku",
        "Uboga mieszczanka z dwójką dzieci",
        "Chłopi-sprzedawcy obroku",
        "Trzech żebraków",
        "Młoda para – dobrze sytuowany mieszczanin- rzemieślnik z żoną",
    };

    private string[] exMessages1 = 
    {
        "Zakon wizytek w 1654 roku sprowadziła z rodzinnej Francji do Warszawy królowa Maria Ludwika Gonzaga, żona Jana Kazimierza. Siostry zostały umieszczone w drewnianym klasztorze w pobliżu pałacu Kazimierzowskiego (obecnie teren Uniwersytetu Warszawskiego), w którym mieszkała królowa. Zakonnice miały służyć ubogim i chorym oraz prowadzić szkółkę dla dziewcząt. Pierwotnym pragnieniem królowej było również, aby siostry założyły dom dla dziewcząt trudniących się nierządem i pomóc im w ten sposób wrócić na właściwą drogę. Obecny kościół wznoszono w dwóch etapach w latach ok. 1728-1733 i 1754-1763 według projektu Karola Baya. Zarysowanie się sklepień kościoła w 1765 roku spowodowało konieczność wymurowania skarp bocznych. Od tamtych czasów świątynia przetrwała w niemal niezmienionym stanie. W jej architekturze wyróżnia się fasada o mocnych efektach światłocieniowych. Dzięki wysunięciu jednych i cofnięciu innych  fragmentów ścian oraz 20 kolumnom sprawia wrażenie, jakby falowała. Rzeźby na fasadzie są dziełem Jana Jerzego Plerscha. Na drugiej kondygnacji znajdują się figury prawodawców zakonu – św. Augustyna i św. Franciszka Salezego. Na trzeciej kondygnacji znajduje się scena Nawiedzenia Najświętszej Marii Panny przez św. Elżbietę, a po bokach figury św. Anny i św. Joachima (rodziców Marii) oraz św. Jana Chrzciciela i św. Józefa (męża Marii). Scena Nawiedzenia (łac. visitatio) nawiązuje do nazwy zgromadzenia sióstr Wizytek – Zakonu Nawiedzenia Najświętszej Marii Panny. Fasadę wieńczą dwa anioły adorujące krzyż. Ponadto nad wejściem do świątyni widoczny jest herb zakonu – serce z hierogramami Jezusa i Marii, przebite strzałami i zwieńczone krzyżem. Nad oknem drugiej  kondygnacji znajdują się herby dobrodziejów zakonu: Wazów – Snopek, i Gonzagów – Dwugłowy Orzeł (przerobiony podczas konserwacji w XIX w. na orła jednogłowego). Na obrazie Canaletta nie ma na drugiej kondygnacji czterech wazonów - dodano je dopiero podczas remontu w połowie XIX wieku. W jednolitym stylowo, późnobarokowym wnętrzu świątyni uwagę przykuwa ambona w kształcie dziobu łodzi. Symbolizuje ona Kościół, którego sternikiem jest Chrystus. W chórze nad fotelem przełożonej umieszczony jest srebrny relikwiarz z sercem fundatorki, królowej Marii Ludwiki Gonzagi. Za klasztorem znajdują się dwa ogrody. W jednym z nich, dostępnym dla zwiedzającym, stoi drewniany dom, w którym przez lata mieszkał ks. Jan Twardowski. Siostry Wizytki jak dawniej żyją w klauzurze, odseparowane od zgiełku tego świata. Warto jeszcze dodać, że na nieistniejących już organach grywał w kościele młody Fryderyk Chopin.",
        "Budynek w stylu dworku polskiego. W połowie XVII wieku na Krakowskim Przedmieściu było około dwustu posesji - w tym jedenaście kamienic, kilkanaście dworków, a na pozostałych stały drewniane chaty. Sto lat później, za czasów Canaletta, przy Krakowskim Przedmieściu stało już kilkadziesiąt kamienic, osiem pałaców, trzy dworki  i kilka zabudowań drewnianych. Przy kościele i klasztorze Wizytek powstało kilka budynków gospodarczych, między innymi spiżarnia, piekarnia i spichlerz.",
        "Przed budynkiem leży stos wielkich okorowanych pni drzew. Ten widok był dość powszechny w XVIII-wiecznej Warszawie i budził żywe zainteresowanie cudzoziemców. Drewno docierało do Warszawy Wisłą, spławiane przez flisaków. Przez pewien czas zostawiano je na powietrzu, aby leżakowało i schło. Następnie, po pocięciu na drobniejsze części, stanowiło opał warszawskich domów. Wisła była głównym szlakiem handlowym dawnej Rzeczypospolitej. Spławiano nią eksportowane do Zachodniej Europy towary: drewno, zboże, sól, futra. W XVII wieku była uważana  za najważniejszą gospodarczo rzekę świata. Dla porównania - taką liczbę przewozów, jaką notowano na niej w końcu XVI i w pierwszej połowie XVII wieku Ren osiągnął dopiero w 1830 roku, a więc dwa wieki później. Znajdowało przy niej zatrudnienie kilkadziesiąt tysięcy osób. Spław z Sandomierza do Gdańska trwał kilka tygodni.",
        "Na pierwszym planie budynek gospodarczy. Być może jest to stajnia albo miejsce, gdzie przetrzymywano czasowo konie. W tle budynek mieszkalny o charakterystycznej szachulcowej konstrukcji. Ścianę tworzą tu drewniane  belki, ułożone w kratownicę i wypełnione mieszaniną gliny  z trocinami, wiórami oraz słomą.  Wypełnienie to było często tynkowane  na biało.",
        "W Warszawie brakowało placów. Dlatego na co dzień handlowano najczęściej na ulicach. Towar rozkładano w koszach i workach  wprost na ziemi lub na drewnianych stołach i straganach. W XVII wieku niewielki placyk przed kościołem Wizytek nosił nazwę Bykowiec dlatego, że handlowano tam bydłem. Sto lat później, za czasów Canaletta, targ stał się tak zwanym rynkiem siennym, na którym handlowano głównie paszą dla koni (sianem, owsem, jęczmieniem, otrębami pszennymi). Zapewne sprzedawano tam również ziarna zbóż i mąkę na potrzeby mieszczan oraz piekarni. Co ciekawe - główny targ koński znajdował się nieopodal, na skrzyżowaniu obecnych ulic: Królewskiej i Marszałkowskiej.",
        "Dwukonna jednoosobowa kareta nazywana była soliterką, egoistką lub  dezobliżantką (od fr. désobligente). Pojazd modny w drugiej połowie XVIII wieku używany na krótkich trasach i do spacerów. Kareta ma resory charakterystycznie wygięte w kształcie litery C. Weszły one do powszechnego użycia w drugiej połowie XVIII wieku, wcześniej do amortyzacji karet używano rzemiennych pasów. Stangret (woźnica) ubrany jest  w strój hajduka z charakterystycznym nakryciem głowy nazywanym mirletonem lub mirlitonem. Określany również jako  czapka skrzydlata lub kołpak skrzydlaty był  wysokim cylindrycznym nakryciem głowy wykonanym z filcu i ozdobionym wstęgą z tkaniny. Niektóre mirletony miały wysokość nawet 60 cm.",
        "Widzimy tu mieszczanina, najprawdopodobniej kupca, który handlował jakimiś trunkami (w ręku trzyma metalowy dzbanek a za nim na wozie widać beczki, być może z trunkami). Mieszczanin ów ubrany jest w strój polski. Żmudne wyliczenia ukazują, że w latach 1750-80 ubiór polski nosiła połowa mieszczan ówczesnej Warszawy. Mieszczanin w odróżnieniu od szlachcica pas nosił na żupanie a nie na kontuszu a zamiast szabli miał tylko drewnianą laskę.  Przedstawiony tu mieszczanin ma na sobie porządny żupan w kolorze niebieskim przepasany raczej nie cennym pasem kontuszowym tylko wąskim pasem siateczkowym zrobionym z miękkiej włóczki. Do tego ma nieodzowne elementy czyli czapkę sukienną, czerwoną obszytą barankiem i długie, czarne buty. Spod żupana widać rąbek białej koszuli.  Jego żona ubrana jest w typowy strój średniozamożnej mieszczanki, który wielokrotnie można oglądać na obrazach Canaletta: biała koszula, brązowy, sznurowany gorsecik, czerwona spódnica do tego biały fartuch. Na głowie podwójny czepek, widać bardzo popularny wśród warszawskich mieszczek: wierzchni czarny a spodni biały.",
        "Szlachcić siedzi na koniu a obok niego stoi osiodłany, biały wierzchowiec, towarzyszą mu dwa psy myśliwskie. Ubrany jest w strój francuski ale już bardzo skromny i uproszczony w którym widać wpływy mody angielskiej. Na głowie ma jeszcze tradycyjny kapelusz tricorne obszyty złotym galonem, spod niego widać upudrowane włosy uczesane w stylu francuskim.  Do tego ma na sobie zielone habit, brązową kamizelkę i białą koszulę. Tradycyjnie te elementy mody francuskiej (habit i kamizelka) były szyte z bardzo kolorowych i drogich tkanin a do tego były przebogato zdobione: haftami, galonami, guzikami.  Tu jednak mamy do czynienia ze strojem bardzo skromnym, bez jakichkolwiek ozdób. Pod wypływem mody na ubiory w stylu angielskim, które były bardzo proste i purystyczne, zaczęły pojawiać się i w modzie francuskiej tak uproszczone stroje. Były one o wiele bardziej praktyczne, tańsze oraz trwalsze niż luksusowa i bogata odzież w stylu francuskim. Bardzo szybko podbiły też gusta Warszawiaków co doskonale widać szczególnie na ostatnich wedutach malowanych przez Bellotta.  ",
        "Widać tu  skromnie ubranego tragarza dźwigającego worek.  Ma on na sobie ciemnożółtą kamizelkę oraz spodnie culotte. Do tego białą koszulę i pończochy  oraz czarne buty z cholewą. W tym okresie wielu mieszkańców Warszawy, szczególnie tych biedniejszych musiało  zadowolić się minimalną ilością odzieży.  Nawet najlichsze wełniane, lniane czy konopne tkaniny były stosunkowo drogie. W związku z tym przeciętny mieszkaniec Polski, jedynie co 10 lat mógł sobie sprawić jakąś sztukę wełnianej odzieży i co najwyżej  jedną koszulę rocznie. Dlatego większość donaszała każdą sztukę odzieży aż do jej rozpadnięcia się w łachmany.",
        "Mieszczanka ubrana jest w strój bardzo skromny i w niezbyt dobrym stanie. Widać tu poszarpaną u dołu oliwkową spódnicę i tak samo zniszczony brązowy kaftan. Na ramionach ma biały szal, którym częściowo owija malutkie dziecko, które nosi na rękach. Do tego dochodzi biały fartuch i biały czepek na głowie.  Towarzyszący jej starszy chłopiec ubrany jest w strój przypominający skromny żupanik, też w niezbyt dobrym stanie i poszarpany u dołu. Spod niego widać spodnią białą koszulinę.",
        "Na placu przed kościołem odbywa się handel. Widać tu wozy i handlarzy, którzy przybyli z pobliskich wsi z sianem, workami zboża, różnymi zwierzętami.  Po środku malownicza grupka czterech sprzedawców obroku.  Są to chłopi odziani w strój, który w tym okresie nazywano sukmanami, kapotami lub siermięgami.  Były to długie, wierzchnie suknie z sukna w różnych kolorach (tu brązowe i szare).  Noszone je w tym okresie luźne, niczym nie przepasane. Na głowach czapki sukienne z barankiem, używane przez chłopów mazowieckich.  Czapki te często były wypychane pakułami. W tym okresie istniały już w strojach ludowych pewne różnice regionalne, jednak nie były one tak wielkie jak w wieku XIX czy początkach XX. ",
        "Weduty Canaletta świetnie oddają kontrasty ówczesnej Warszawy. Nie brakuje na nich licznych przedstawień różnego rodzaju pospólstwa miejskiego np. żebraków. Podobno wbrew pozorom był to intratny interes bo do Warszawy przybywała ogromna rzesza bogatej szlachty i magnaterii, która był skłonna sypnąć groszem. Stąd w pobliżu ważnych kościołów czy klasztorów zawsze można dostrzec charakterystyczne sylwetki bosych, obdartych nędzarzy odzianych w łachmany tak jak na tym obrazie.  Wszyscy trzej żebracy ubrani są w łachmany będące pozostałościami po jakiś koszulach, kaftanach, kamizelkach. Mają długie nieporządne włosy i brody. Jeden z żebraków po lewej, nosi oprócz tego charakterystyczną torbę i wspiera się na kosturze żebraczym.",
        "Ukazana tu mieszczka to prawdziwa modnisia. Ubrana jest w stylu francuskiej mody mieszczańskiej, która dość szybko trafiła na salony i była też noszona przez wielkie damy ze względu na swój wygodny i praktyczny charakter. Ma ona na sobie biały żakiecik typu caraco z charakterystyczną baskinką a do tego białą spódnicę. Na ten strój zarzuciła tzw. półsalopę czyli luźne okrycie z kapturem sięgające do pół uda. Najczęściej w kolorze czarnym, szyte z porządnych ale i drogich  materiałów np. jedwabiu. Na głowie ma biały spodni cornet obszyty falbanką a na to bardzo popularny w tym okresie we Francji czepiec tzw. calèche. Był to obszerny rodzaj czepca w formie składanego kaptura, który można było składać i stawiać tak jak budę w kolasce czy powozie, stąd jego francuska nazwa. Czepiec z boku ozdobiony jest czerwoną wstążką. W ręku modnisia trzyma wachlarz a na nogach do białych pończoch nosi czarne trzewiki z metalową klamerką.  Przedstawiony tu mieszczanin-rzemieślnik jest ubrany w strój w stylu mody angielskiej. Uwagę zwraca rodzaj ciemnobrązowego płaszcza frakowego  z żółtymi wyłogami i taką podszewką. Wyłogi są ozdobione metalowymi guzikami tak typowymi dla mody angielskiej. Pod spodem widać jasną kamizelkę i białą chustkę związaną na szyi. Na nogach skórzane buty z bardzo wysokimi cholewami po bokach zapinane na  takie same guziki jak na płaszczu frakowym. Do tego czapka w stylu polskim obszyta ciemnym barankiem.  Spod niej widać fryzurę z własnych niepudrowanych włosów-tak typową dla zwolenników mody angielskiej.  Dla mieszczaństwa warszawskiego, jak opisują przybywający do ówczesnej Warszawy turyści, bardzo charakterystyczne było mieszanie takich elementów. Często jedna osoba miała na sobie kilka strojów w różnym stylu: polskim, francuskim, angielskim a nawet elementy strojów bliskowschodnich. Było to związane m.in. z tym, że wielu mieszczan zaopatrywało się w potrzebne akurat im elementy ubioru na aukcjach gdzie wyprzedawano rzeczy należące do osób, które zbankrutowały albo nie pozostawiły testamentu. W ówczesnej Warszawie kwitł również handel używaną odzieżą a nawet tą ukradzioną, która była bardzo cennym łupem.",
    };

    private string[] headers2 = { };

    private string[] messages2 = { };

    private string[] exHeaders2 = 
    {
        "Kościół Karmelitów",
        "Pałac Radziwiłłów (Namiestnikowski)",
        "Ratusz jurydyki Dziekanki",
        "Stara Dzwonnica",
        "Budynek gospodarczy",
        "Kramy",
        "Stangret",
        "Dwie kumoszki, niezamożne mieszczanki",
        "Szlachcic na koniu",
        "Karmelici",
        "Rzemieślnicy ",
        "Rodzina zamożnych mieszczan lub przedstawiciel tzw. wolnych zawodów np. lekarz  z żoną i synkiem.",
        "Para szlachciców"
    };

    private string[] exMessages2 = 
    {
        "Kościół pod wezwaniem Wniebowzięcia Najświętszej Marii Panny i św. Józefa Oblubieńca został zbudowany w latach 1661–1681 prawdopodobnie według projektu Constantino Tencalli, jednego z autorów koncepcji Kolumny Zygmunta. Kościół ma plan krzyża i jednoprzestrzenną nawą z głębokimi kaplicami po bokach sprawiającymi wrażenie naw bocznych.  Karmelici, zakon pustelniczy i klauzurowy, przybyli do Polski w 1605 roku, a do Warszawy - na zaproszenie króla Władysław IV - w 1634 roku. Usadowili się przy Krakowskim Przedmieściu, a ich głównym posłaniem było nauczanie okolicznych mieszkańców. W XVIII wieku urządzali w kościele publiczne dysputy teologiczne. Kościół postawiono w stylu barokowym, ale nie zbudowano fasady. Wzniósł ją dopiero w latach 1762-1780 Efraim Szroeger w stylu wczesnego francuskiego klasycyzmu. Fasadę ufundował właściciel sąsiadującego z kościołem pałacu - Karol Radziwiłł „Panie Kochanku”. Była to pierwsza w Warszawie kamienna klasycystyczna fasada. Główne wejście zdobi wykuty z czarno-zielonkawego marmuru portal, nad nim umieszczony jest kartusz z herbem Radziwiłłów (trąby radziwiłłowskie) przypominający o fundatorze fasady. Kondygnację wyżej umieszczone są dwie niewielkie ażurowe dzwonnice przypominające wazony. Szczyt fasady wieńczy wielki miedziany glob.  Oplata go wąż z jabłkiem w pysku przyciśnięty kielich z Hostią, co symbolizuje Wiarę i zwycięstwo Chrystusa nad szatanem. Wielka miedziana kula spowodowała, że utarło się w dziewiętnastowiecznej Warszawie powiedzenie: „spuchnąć jak karmelicka bania”. Klasztor karmelicki skasowano zaraz po powstaniu styczniowym, a budynek przejęło  seminarium duchowne, które ma tu siedzibę do dzisiaj.",
        "Budowę korpusu głównego w miejscu znajdującego się tu wcześniej dworu rozpoczął ok. 1643 roku hetman wielki koronny Stanisław Koniecpolski. Pierwotnie był to barokowy pałac z obszernym ogrodem typu włoskiego, schodzącym aż do Wisły, płynącej wówczas znacznie bliżej skarpy.  Budynek był kilkakrotnie przebudowywany. W połowie XVIII wieku od strony ulicy wzniesiono skrzydła boczne okalające rozległy dziedziniec. Po Koniecpolskich pałac stanowił własność Lubomirskich i Radziwiłłów. Odbywały się tu liczne uczty i bale. Jednym z najbardziej znanych jego mieszkańców był książę Karol Radziwiłł zwany Panie Kochanku, najzamożniejszy polski magnat drugiej połowy XVIII wieku i jeden z najbogatszych ludzi ówczesnej Europy. Wojewoda wileński, nazywany również „niedźwiedziem litewskim”, znany był z ekstrawaganckich pomysłów. Pewnego razu zajechał na Zamek Królewski w odwiedziny do Stanisława Augusta karetą zaprzężoną w cztery niedźwiedzie wzbudzając powszechną panikę.  Poróżniony z Czartoryskimi i królem przestał bywać w stolicy, a pałac zaczęto wynajmować, co przynosiło spory dochód. W  latach 1773-1818 z przerwami był wynajmowany na cele teatralne. W 1778 roku odbyła się tu premiera polskiej opery Nędza uszczęśliwiona, a w latach 1804–1806 występował  zespół Wojciecha Bogusławskiego.  W styczniu 1807 roku na przedstawieniu sztuki Andromeda gościł tu Napoleon Bonaparte, a w 1815  zatrzymał się w nim car Aleksander I. 24 lutego 1818 roku w pałacu odbył się pierwszy publiczny koncert ośmioletniego Fryderyka Chopina. W 1818 roku pałac został odkupiony przez rząd Królestwa Polskiego z przeznaczeniem na siedzibę namiestnika Królestwa Polskiego, a także na biura i mieszkania urzędników. Wówczas  zaczęto nazywać go pałacem Namiestnikowskim. Równocześnie Chrystian Piotr Aigner gruntownie przebudował gmach w stylu klasycystycznym, nadając mu obecny wygląd. W drugiej połowie XIX wieku jego największe pomieszczenie – Salę Balową – udostępniano na wystawy. W 1879 roku pokazano tu po raz pierwszy w Warszawie Bitwę pod Grunwaldem  Jana Matejki. W okresie międzywojennym pałac był oficjalną siedzibą premiera i rządu.  W czasie okupacji Niemcy urządzili tu Deutsches Haus - centralną placówkę społeczno-kulturalną dla Niemców w Warszawie. W skrzydłach bocznych działał luksusowy hotel z kasynem i restauracją, a w pomieszczeniach dawnej stajni - piwiarnia w stylu niemieckim. W lutym 1944 roku w Sali Balowej wystawiono ciało kata Warszawy Franza Kutschery, który zmarł od ran odniesionych w zamachu. Po wojnie pałac również pełnił funkcje rządowe.  W 1955 roku został tu podpisany Układ Warszawski, a w 1989 odbywały się obrady Okrągłego Stołu. Siedzibą Prezydenta Rzeczypospolitej Polskiej stał się w 1994 roku. Otrzymał wówczas nową oficjalną nazwę – pałac Prezydencki.",
        "Budynek wykonany w technice muru pruskiego, zbliżonej do konstrukcji szachulcowej, ale bardziej trwałej. O ile w konstrukcji szachulcowej konstrukcja z drewnianych belek wypełniana jest mieszaniną gliny, trocin lub słomy, o tyle w murze pruskim wypełnienie stanowią trwalsze cegły. Ratusz był siedzibą władz jurydyki – z niezależnymi od Starej i Nowej Warszawy rajcami, sądem i burmistrzem.  Jurydyki zostały zlikwidowane dopiero w roku 1791, co znacznie ułatwiło rozwój miasta. W XIX wieku na miejscu zburzonego ratusza  powstał skwer, na którym 24 grudnia 1898, roku w stulecie urodzin Adama Mickiewicza, odsłonięto jego pomnik. ",
        "Niewielka dzwonnica starego kościoła pochodzi z około 1680 roku. Została postawiona na sposób włoski jako skromna kampanila, czyli wyodrębniona z bryły kościoła lub budowana obok niego.",
        "O tym, że jest to budynek gospodarczy, a nie mieszkalny świadczy przede wszystkim brak na dachu kominów -  pozbawiony był on więc ogrzewania. Na parterze widoczne są drzwi wejściowe i okna z drewnianymi okiennicami. Znajdujące się nad nimi zadaszenie, podobne do zadaszeń w sąsiednich kramach, sugeruje, że część tego budynku była wykorzystywana do celów handlowych. Być może budynek służył jako magazyn dla kramów znajdujących się przy ogrodzeniu kościoła Karmelitów. ",
        "Do muru kościelnego niczym narośle przylegają skromne kramy, z których część dochodów mogła wpływać do kasy zakonu Karmelitów. Prawdopodobnie teren przed kościołem stawał się gwarnym targiem w dzień odpustu, który w tym przypadku przypadał na dzień 15 sierpnia, jako że kościół był pod wezwaniem Zaśnięcia (obecnie Wniebowzięcia) Najświętszej Maryi Panny i świętego Józefa Oblubieńca. Właśnie na ten dzień przypadają kościelne obchody tego święta.",
        "Stangret powożący karetą ubrany jest w liberię w stylu francuskim. Składa się ona z habit i spodni typu culotte w kolorze szarym. Na głowie czarny kapelusz tricorne. Wszystkie te elementy zostały ozdobione złotym galonem- czyli tkaną lub plecioną taśmą całkowicie lub z dodatkiem metalowych nici. Na nogach białe pończochy i czarne pantofle z klamrą. Ponieważ w tym okresie nie każda męska łydka dobrze prezentowała się w takiej jasnej pończosze, panowie często wkładali sobie w nie tzw. fałszywe łydki czyli specjalne wkładki wypełnione łabędzim puchem.",
        "Widzimy tu dwie kumoszki pogrążone w rozmowie, przedstawicielki tzw. drobnego mieszczaństwa, żony, córki –rzemieślników pośledniejszych zawodów. Jedna z nich ta po lewej ubrana jest w typowy, letni strój niezamożnej mieszczanki czyli białej koszuli, stanika czy też gorsetu bez rękawów, szerokiej spódnicy bez falban w kolorze niebieskim oraz białego płóciennego fartucha i skromnego, płóciennego czepka, głęboko nasuniętego na włosy, tak bardzo różnego od modnych i wymyślnych kornetów noszonych przez bogate mieszczanki, szlachcianki czy arystokratki. Druga z kobiet ukazana z profilu,  również nosi typowy strój drobnej mieszczki- tym razem mam jednolity kaftan w kolorze niebieskim, pasowany w talii i szeroką, marszczoną spódnicę w kolorze czerwonym. Na głowie ma czepek w typie staropolskiego, niewieściego kołpaczka: brązowy, sukienny obszyty czarnym futrem a pod nim widać  biały płócienny. Na nogach widać czarne trzewiki z dłuższym noskiem.",
        "Szlachcic dumnie trzymający się na koniu ubrany jest w oliwkowy kontusz z odrzuconymi rozcinanymi rękawami (tzw. wyloty). Pod nimi widać piaskowe w kolorze rękawy od żupana. Na głowie czapka- kołpak w kolorze żupana obszyta barankiem. Z boku widać szablę zw. też karabelą i długie, czarne buty z cholewami. Na twarzy szlachcica widać pięknego wąsa, który był obowiązkowym elementem do stroju polskiego. Niestety staropolski, sarmacki wąs sumiasty nie wzbudzał entuzjazmu ówczesnych dam, które często kazały swym wybrankom je golić a do tego przebierać się po francusku. Jak pisał Franciszek Kniaźnin w „Odzie do wąsów”: „Ozdobo twarzy, Wąsy pokrętne! Powstaje na Was ród zniewieściały. Dworują sobie dziewczęta wstrętne, Od dawnych Polek dalekie chwały. […] Kogo wstyd matki, ojca i braci, Niech się ze swego kraju natrząsa. Ja zaś z ojczystej chlubien postaci, Żem jeszcze Polak, pokręcę wąsa.”",
        "Przed kościołem widać dwóch zakonników karmelitów.  Ich strój składa się z tuniki, szkaplerza i kaptura  koloru brązowego. Jeden z nich ma dodatkowo założony biały płaszcz z kapturem, który jest też  elementem stroju tych zakonników i zakładany jest w określonych okolicznościach np. na mszę świętą. Początkowo karmelici, którzy są zakonem powstałym w Ziemi Świętej nosili płaszcze w pasy. Jednak po przybyciu do Europy ten element ich garderoby wzbudzał wielkie kontrowersje, pasiaste tkaniny były uważane za tzw. diabelską materię.  W związku z tym papież Aleksander IV nakazał karmelitom zmienić płaszcz w pasy na jednobarwny. I  tak po długich sporach i oporach, w roku 1287 w dzień św. Marii Magdaleny, bracia postanowili zrezygnować z płaszcza w „diabelskie paski” na rzecz białej peleryny.  Na czubku głowy obydwu zakonników doskonale widoczne są tonsury- czyli wygolony krążek na czubku głowy, włosy okrążające wygolone miejsce miały przypominać koronę cierniową. Tonsura była w kościele katolickim znakiem przynależności do stanu duchownego.",
        "Rzemieślnicy w ciemnych kurtkach i długich fartuchach.  Ten po prawej nosi czapkę w stylu polskim obszytą barankiem. Ten ukazany po lewej ma włosy uczesane w modną fryzurę tzw. pig tail- świński ogonek. Długie włosy zaczesane do tyłu na gładko i mocno skręcone w sztywny ogonek, który mógł być przewiązany i owinięty czarną wstążką.  Fryzura ta pojawiła się w Anglii i była bardzo popularna zwłaszcza w XVIII wieku, szczególnie chętnie nosili ją marynarze, prawnicy, żołnierze ale też i przedstawiciele innych zawodów i warstw społecznych.",
        "Mężczyzna ubrany jest w skromnym stylu angielskim, który szczególnie w ostatniej ćwierci XVIII wieku stanowił bardzo atrakcyjną alternatywę dla bogatej ale niewygodnej i bardzo kosztownej mody francuskiej. Stroje w stylu angielskim były szczególnie chętnie noszone przez mieszczan, kupców, rzemieślników i przedstawicieli tzw. wolnych zawodów np. lekarzy. Mężczyzna ma tu na sobie  pozbawiony ozdób płaszcz frakowy oraz brązowy frak z typowymi dla tej mody metalowymi, skromnymi guzikami (najsłynniejsze były te z Birmingham z manufaktury Matthew Boulton`a) , krótką kamizelkę z błękitnym wyłogiem, spodnie bryczesy- mogą być skórzane i długie buty tzw. top-boots. Na głowie okrągły, angielski kapelusz tzw. beaver hat (robiony z filcu na bazie sierści bobra) z charakterystyczną ozdobną klamrą. Jego żona ma na sobie skromny strój będący połączeniem mody francuskiej i angielskiej. Widać tu żakiecik z baskinką tzw. caraco i spódnica w kolorze musztardowym. Dekolt przysłonięty jest białą, gazową chusteczką tzw. fichu, na ramionach czarny szal a na głowie modny gazowy lub muślinowy czepek z długimi borbami- czyli wąskimi koronkami, ozdobiony kwiatami.  Kwiaty te mogą być sztuczne, tego typu ozdoby były bardzo popularne w tym okresie, wykonywali ją specjalni rzemieślnicy z drucików, jedwabiu, szklanych kulek a nawet kokonów jedwabników. Chłopczyk ubrany jest w strój będący kopią ubiorów dorosłych mężczyzn. Ma na sobie brązową kamizelkę i spodnie culotte oraz białe pończochy i koszulę. Włosy obcięte na krótko. W tym okresie dzięki wpływom angielskim, pojawiły się już pierwsze stroje szyte specjalnie dla dzieci, szczególnie tych młodszych ale starsi chłopcy jeszcze często nosili ubrania będące kopią strojów ich ojców. ",
        " Para szlachciców ubranych w stroje polskie. Obydwaj mężczyźni noszą kontusze z nałożonymi wylotami (rozcinanymi rękawami) w kolorze brązowym i czerwonym do tego czapki kołpaki w tym samym kolorze obszyte barankiem. Przy ważnych uroczystościach rękawy od kontusza był pięknie upięte z tyłu na plecach. Potrącenie innego szlachcica, luźno zwisającymi wylotami, uważane było za zniewagę, która wymaga pomszczenia często z szablą w ręku. U jednego z nich widać również wyraźnie pas kontuszowy i szablę przy boku."
    };

    private string[] headers3 = { };

    private string[] messages3 = { };

    private string[] exHeaders3 =
    {
        "Pałac Biskupów Krakowskich",
        "Pałac Teppera",
        "Kościół Kapucynów",
        "Pałac Radziwiłłów (pałac Paca)",
        "Pałac Borchów",
        "Pałac Krasińskich (Pałac Rzeczypospolitej)",
        "Pałac Branickich",
        "Sprzedawca miedziorytów.",
        "Kareta sześciokonna",
        "Stangret",
        "Służący i jeździec z koniem",
        "Dwóch Żydów",
        "Niezamożna mieszczanka  z dzieckiem",
        "Zamożna mieszczanka z dzieckiem",
        "Stangret i lokaje oraz magnat we wnętrzu karety",
        "Foryś",
        "Dwóch laufrów",
        "Szlachcic i duchowny",
    };

    private string[] exMessages3 = 
    {
        "Budowę pałacu rozpoczęto w 1622 roku dla biskupa krakowskiego Jakuba Zadzika. Był oficjalną rezydencją warszawską biskupów krakowskich, którzy jako senatorowie duchowni brali udział w pracach senatu Rzeczypospolitej. Po zniszczeniach w czasie wojen szwedzkich został odbudowany w 1668 roku dla biskupa Andrzeja Trzebickiego. Ponieważ jednak rzadko był wykorzystywany za panowania Sasów, rezydujących głównie w Dreźnie, budynek mocno podupadł i w połowie XVIII wieku wymagał gruntownego remontu. W latach 1760–1762 został poddany całkowitej przebudowie z inicjatywy biskupa Kajetana Sołtyka - najprawdopodobniej według projektu Jakuba Fontany. W tym czasie pałac przybrał szatę późnobarokową. Jest on przykładem stosunkowo mało rozpowszechnionego w Warszawie typu pałacu – pałacu przyulicznego – wzniesionego w linii zabudowy ulicy i na wysokość jednego piętra. To właśnie na pierwszym, bardzo wysokim, piętrze  znajdowały się sale reprezentacyjne. Po trzecim rozbiorze oznaczającym likwidację polskiego sejmu i senatu pałac przestał pełnić swą pierwotną funkcję jako siedziba biskupów krakowskich w stolicy. Ulokowano więc tu najpierw liczne urzędy, a następnie przekształcono w kamienicę czynszową. Zburzony w 1944 roku w czasie powstania warszawskiego został odbudowany na podstawie widoku uwiecznionego na obrazie Canaletta. Przy jego bramach zachowały się dwa oryginalne gaśniki do pochodni.",
        "Nieistniejący pałac przy ul. Miodowej 7 w Warszawie. Budynek został wzniesiony w 1774 roku według projektu Efraima Schroegera. Był jednym z nielicznych pałaców Warszawy, który nie należał do któregoś z magnackich rodów, ale do zamożnego mieszczanina Piotra Teppera. Potężna, prosta bryła pałacu z dwoma narożnymi ryzalitami przypominała – jak mówiono – wielką skrzynię. Budynek uważa się za pierwszą w Warszawie nowoczesną kamienicę okresu kapitalizmu. Na parterze mieścił się kantor bankowy, na pierwszym piętrze apartament do wynajęcia, a na drugim – apartament właścicieli. Razem z Piotrem Tepperem mieszkał jego adoptowany siostrzeniec, Piotr Fergusson-Tepper, który stopniowo przejął interesy wuja. Był bankierem i wierzycielem króla Stanisława Augusta, najbogatszym warszawskim finansistą drugiej połowy XVIII wieku. Król za jego pośrednictwem zaciągał i spłacał pożyczki, m.in. na takie inwestycje jak budowa Łazienek. Fergusson-Tepper, chcąc dorównać arystokracji, prowadził wystawne życie. Gościł króla, arystokratów, ambasadorów i cudzoziemskich posłów. O jego żonie powiadano, że bieliznę do prania wysyła do Paryża. Kiedy w 1793 roku nastąpił krach na polskim runku finansowym - zbankrutował. W pałacu Teppera odbyła się licytacja jego majątku. W kwietniu 1794 roku tłum warszawiaków oskarżających bankiera o celowe wywołanie kryzysu finansowego w kraju napadł i splądrował gmach. Raniony w głowę bankier zmarł kilka dni później. W XIX wieku budynek często zmieniał właściciela. W 1807 roku w pałacu odbył się bal na cześć Napoleona I. W latach 1815–1818 pierwsze i drugie piętro zajmowała Komisja Rządowa Przychodów i Skarbu. W latach 1856–1862 mieszkała tu pisarka i emancypantka Narcyza Żmichowska, a w 1899 urodził się wybitny poeta międzywojnia Jan Lechoń. Pałac spłonął we wrześniu 1939 roku. W 1948 roku został do końca rozebrany w związku z budową Trasy W-Z, jako że znajdował się bezpośrednio nad planowanym tunelem. Gdyby chcieć zachować pałac, należałoby tunel wydłużyć, co znacznie podniosłoby koszty inwestycji. Podczas rozbiórki piwnic znaleziono znaczne ilości wyborowych win i wódek, zmagazynowanych tam jeszcze przed wybuchem wojny przez znaną warszawską firmę winiarską Simon i Stecki.",
        "Kościół Przemienienia Pańskiego zwyczajowo nazywany jest kościołem Kapucynów. Powstał wraz z klasztorem w latach 1683–1694 z inicjatywy króla Jana III Sobieskiego jako wotum dziękczynne za zwycięstwa nad Turkami pod Chocimiem i pod Wiedniem. Kamień węgielny pod budowę świątyni wmurował sam król tuż przed wyruszeniem na wyprawę pod Wiedeń, składając  przy tym uroczystą przysięgę jego dokończenia po zwycięskim powrocie. Ze względu na regułą zakonną  św. Franciszka, która wymaga ubóstwa, powstała skromna świątynia z prostotą fasadą zwieńczoną trójkątnym szczytem, zaś jego jedyną ozdobę stanowi herb Sobieskich – Janina. Warto podkreślić, że pierwszy, znacznie okazalszy projekt świątyni został przez zakonników odrzucony jako zbyt wystawny. Zanim król Jan III został po śmierci złożony na Wawelu, jego ciało przez 30 lat spoczywało właśnie u Kapucynów. Ostatecznie zostało tu  tylko jego serce. Obecnie znajduje się w Kaplicy Królewskiej obok urny z wnętrznościami króla Augusta II Mocnego. W 1780 roku w podziemiach kościoła Kapucynów lub na przykościelnym cmentarzu został pochowany także Canaletto. Po jego grobie nie zachował się jednaj żaden ślad. Dziś świątynia znana jest głównie z ruchomej szopki, która po raz pierwszy został zaprezentowana warszawiakom w 1948 roku.",
        "Pałac stojący w głębi posesji  został postawiony w latach 1681-1687 w stylu barokowym dla Dominika Mikołaja Radziwiłła według projektu Tylmana z Gameren. W połowie XVIII wieku  wzniesiono nowe oficyny przy ul. Miodowej według projektu Jakuba Fontany. W latach 1762-1775, kiedy pałac był w dzierżawie u Michała Fryderyka Czartoryskiego,  często gościł w nim król Stanisław August Poniatowski. 3 listopada 1771 roku, po wyjeździe z pałacu, król został porwany przez konfederatów barskich. Szczęściem, po nocy spędzonej we młynie na Marymoncie, wrócił cały i zdrowy na Zamek. W  1823 roku pałac zakupił generał, Ludwik Michał Pac, dla którego został przebudowany w stylu klasycystycznym - według projektu Henryka Marconiego. Prócz klasycyzmu we wnętrzach zastosowano również dekoracje o charakterze neogotyckim i mauretańskim. Dwa pawilony od strony ulicy zostały wówczas połączone półkolistą, wklęsłą bramą ozdobioną fryzem przedstawiającym rzymskiego konsula. Za udział w powstaniu listopadowym pałac został skonfiskowany generałowi Pacowi przez władze carskie. Obecnie cały kompleks budynków mieści Ministerstwo Zdrowia.",
        "Pałac przy ul. Miodowej 17/19 został wzniesiony w pierwszej połowie XVIII wieku dla  barona Piotra de Riaucourta. Formę klasycystyczną nadał mu ok. 1780 roku Dominik Merlini na zlecenie nowego właściciela, podkanclerzego koronnego, Jana Borcha.  Plan pałacu ma kształt podkowy. Od ulicy odgradza go oryginalne ażurowe ogrodzenie i brama z żelaza. Na tyłach pałacu powstał regularny ogród francuski, który istnieje do dziś, chociaż w zmienionej formie. W 1843 roku pałac przeznaczono na siedzibę arcybiskupów warszawskich. W 1953 roku został tu aresztowany kardynał Stefan Wyszyński, który po uwolnieniu z internowania - w 1956 roku - mieszkał w nim do śmierci. ",
        "Pałac został wzniesiony w stylu barokowym w latach 1677–1694 dla wojewody płockiego Jana Dobrogosta Krasińskiego. Architektem pałacu, najlepszej świeckiej budowli barokowej w Warszawie, był Tylman z Gameren. Tympanony w środkowej części budynku wypełniają dekoracje rzeźbiarskie dłuta Andrzeja Schlütera. Nawiązują one do historii rzekomego antycznego protoplasty rodu Krasińskich - Marka Waleriusza Korwinusa. Od strony placu walczy on z Galami, od strony ogrodu wjeżdża triumfalnie do Rzymu. Pierwotnie dach pokryty był dachówką, tak jak pokazuje obraz Canaletta. Jednak po pożarze w 1783 roku zabezpieczony został  blachą, i tak pozostało do dziś. W 1765 pałac został zakupiony przez Rzeczpospolitą na siedzibę Komisji Skarbowej Koronnej. Od tej pory nosi nazwę Pałacu Rzeczypospolitej. W XIX wieku był siedzibą sądów, w okresie międzywojennym nawet Sądu Najwyższego. Obecnie mieszczą się tu zbiory specjalne Biblioteki Narodowej.  Znajdujący się za pałacem ogród został założony w końcu XVII wieku. Udostępniony mieszkańcom stolicy już w 1766 roku w pierwszej połowie XIX stulecia stał się ulubionym miejscem spacerów i wypoczynku warszawiaków.",
        "Pałac został wzniesiony w latach 40. XVIII wieku dla hetmana wielkiego koronnego Jana Klemensa Branickiego. Jego projektantem był Jan Zygmunt Deybl, który po zatargu z fundatorem został odsunięty od budowy i zastąpiony przez  Jana Henryka Klemma. Późnobarokowy pałac składa się z korpusu głównego i skrzydeł bocznych tworzących obszerny dziedziniec honorowy od strony Podwala. Od ulicy Miodowej widoczna jest zatem jego tylna elewacja. Po śmierci hetmana w pałacu mieszkała jego trzecia żona, Izabella Poniatowska, siostra króla Stanisława Augusta. W XIX wieku pałac zmieniał właścicieli i użytkowników. Od strony Miodowej na parterze funkcjonowały sklepy, działał tu rękawicznik, optyk i księgarnia.  W końcu pałac stał się czynszową kamienicą. Po wojnie został odbudowany na podstawie widoku utrwalonym na obrazie Canaletta. Przez wiele lat służył Urzędowi m.st. Warszawy, zanim w 2009 roku nie został zwrócony spadkobiercom, którzy po kilku latach sprzedali go deweloperowi.",
        "W Warszawie drugiej połowy XVIII wieku istniał już rynek handlu dziełami sztuki. Widoczny na obrazie mężczyzna wywiesił na ceglanym murze na rogu ulicy Senatorskiej miedzioryty, które nazywano wówczas kopersztychami. W ten sposób potencjalni klienci mogli zapoznać się  z ofertą i łatwiej dokonać wyboru. Grafiki, znacznie tańsze od malarstwa, znajdowały nabywców wśród większej grupy miłośników sztuki. Obnośny handel odbitkami graficznymi istniał w Europie Zachodniej już w XVI wieku, w Polsce pojawił się nieco później. Prócz tego  funkcjonowała tu również sprzedaż dzieł sztuki prowadzona przez magazyny handlowe. Nie jest wykluczone, że siedzący pod murem sprzedawca, sprawiający wrażenie trochę znudzonego,  jest „przedstawicielem handlowym” kantoru w pałacu Teppera, który znajdował się w tuż obok pałacu Biskupów Krakowskich. W kantorze tym, w 1778 roku znajdowała się pokaźna liczba obrazów (około 180) oraz inne dobra luksusowe związane z wyposażeniem wnętrz. Najważniejsze miejsca ówczesnej  Warszawy, w których można było nabyć dzieła sztuki i inne towary luksusowe to: Marywil, magazyn Henryka Jarzewicza, pałac Teppera, kamienice Roeslera i Hurtyga, pałac Radziwiłłowski na Krakowskim Przedmieściu, pałacu Sułkowskiego oraz Ratusz Starego Miasta. Sam handlarz, widoczny tu w popiersiu, to mężczyzna ubrany dość nieformalnie, nosi tylko białą koszulę i beżową kamizelkę, pokazywanie się w takim stroju publicznie uchodziło za złamanie norm obyczajowych. Na głowie ma czapkę tzw. szlafmycę czyli nakrycie głowy zakładane do snu. W tym okresie tego typu nakrycia głowy były też noszone po domu gdy mężczyzna chodził w nim bez peruki.",
        "Zarówno liczba koni w zaprzęgu, jak i bogate zdobienia samej karety wskazują, że podróżuje nią osoba bardzo wysoko postawiona w hierarchii społecznej. Podkreśla to również duża grupa towarzyszących jej służących. Oprócz dwóch lokajów z tyłu, kareta „obsługiwana”  jest przez stangreta (woźnicę), któremu pomaga siedzący na koniu z przedniej pary pomocnik nazywany forysiem (od niem. Vorreiten czyli poprzedzać konno). Przed karetą widać jeszcze dwóch biegnących służących zwanych lauframi - w strojach hajduków. Ich zadaniem było usuwanie z drogi przedmiotów, bądź ludzi blokujących płynny przejazd karety i jej pasażera. ",
        "Stangret powożący karetą ubrany jest w strój w stylu francuskim. Widać tu habit i spodnie culotte w niebieskim kolorze. Habit jest wyjątkowo bogato zdobione złotym galonem. Na głowie czarny kapelusz tricone również zdobiony złotym galonem. Włosy uczesane w stylu francuskim i przewiązane z tyłu czarną wstążką. Na nogach białe pończochy i długie, czarne buty z cholewami.",
        "W drzwiach Pałacu Biskupów Krakowskich widać najprawdopodobniej trzech służących niższej rangi, którzy nie dostawali od swoich pracodawców reprezentacyjnych liberii. Ubrani są oni w bardzo popularne wśród biedniejszych mieszkańców Warszawy luźne kaftany. Do tego noszą polskie czapki obszyte barankiem. Postać ukazana na koniu tyłem ubrana jest we francuskie habit zdobione srebrnym galonem.",
        "Po środku ulicy stoi  dwóch Żydów pogrążonych w rozmowie. Można ich rozpoznać po charakterystycznych, wysokich futrzanych czapkach, ciemnych strojach oraz długich brodach i włosach.  Strój i wygląd Żydów w  Polsce w wieku XVIII bardzo różnił się od ubioru powszechnie noszonego w naszym kraju. W oczy szczególnie rzucały się długie włosy i bujne brody, wyglądające bardzo egzotycznie na tle wygolonych czupryn i sumiastych wąsów naszej szlachty ale też i chłopów.  Dawało to- jak zauważył jeden z posłów na Sejm Wielki- okazję pospólstwu naszemu do nienawiści i wzgardy tego narodu. Dlatego postulowano o ubiorową asymilację Żydów. ",
        "Stan mieszczański, podobnie jak szlachecki był bardzo zróżnicowany, szczególnie pod względem majątkowym co świetnie widać na wedutach Canaletta.  Przedstawiona tu niezamożna mieszczanka ubrana jest w jednolity kaftan i długą spódnicę w kolorze jasnobrązowym. Na głowie ma podwójny czepek- wierzchni czarny przewiązany brązową wstążką, pod spodem biały, płócienny. Jest on głęboko nałożony na głowę i nie widać spod niego włosów. Taki sposób jego noszenia był charakterystyczny dla biedniejszych mieszczanek. Szyję okrytą ma niebieską chusteczką a na spódnicy zielony fartuch. Tego typu dodatki były też typowe dla niezamożnych mieszczanek, które często pomagały w warsztatach swoim mężom czy stały za ladami kramów, nie wspominając o tym, że to na nich spoczywał głównie ciężar prowadzenia gospodarstwa domowego.  Na nogach ma ciężkie, czarne pantofle. Dziecko, które trzyma na ręku ubrane jest w jakąś brązową koszulinę, być może przerobioną ze starego odzienia matki lub ojca.",
        "Mieszczanka ubrana jest w lekką, łososiową suknię w stylu francuskich sukni uproszczonych, które weszły w modę w drugiej połowie lat 70. XVIII wieku. Były one noszone bez szerokich usztywnień typu panier- czyli płóciennych spódnic, z wszytymi trzema wiklinowymi obręczami, noszonymi na biodrach. W Polsce nazywano je rogówkami. Do tego nosi bardzo modne dodatki: czarny szal i płócienny lub muślinowy, biały czepek na głowie ozdobiony błękitną wstążką. Czepki zwane też kornetami były w tym okresie niezwykle pożądanym dodatkiem modowym. Ilość wzorów była ogromna, podobnie jak i zdobień. Dziewczynka, które towarzyszy mieszczce nosi jasną sukieneczkę, do której przyszyto białe lejce, które w tym okresie służyły do podtrzymywania dziecka w czasie nauki chodzenia. Na główce ma czepek podobny do matczynego.",
        "Widać tu wystawną karetę z poszóstnym zaprzęgiem poprzedzaną przez dwóch laufrów (6.b) i czterech służących ze stangretem, forysiem (6.a) i dwoma lokajami z tyłu. W środku widać ważną personę, być może jakiegoś magnata bo ulica Miodowa (zwana wtedy Kapucyńską) była ulicą magnackich rezydencji. Ubrany jest on najprawdopodobniej w europejski wariant stroju orderowego Orderu Orła Białego, którego błękitna szarfa z lewego ramienia na prawy bok przepasuje jego tors. Strój ten w wariancie europejski składał się z białej kamizelki i czerwonego habit a w wariancie polskim z białego żupana i czerwonego kontusza. Zarówno stangret jak i dwaj lokaje na koźle są ubrani w liberie  według mody francuskiej. Ich wygląd, fason i zdobienia były zależne od fortuny  pana, który ową służbę utrzymywał. Tu mamy eleganckie francuskie habit w musztardowym kolorze, czerwone kamizelki i takie spodnie do kolan tzw. cullote.  Zarówno habit jak i kamizelki zdobione są srebrnymi galonami. Na głowach francuskie kapelusze typu tricorne (u nas zwane trójgraniastymi) również obszyte srebrnym galonem. Na nogach białe pończochy i wysokie buty z cholewami w kolorze czarnym.",
        "Foryś,  był pomocnikiem stangreta powożącego  wielokonnym zaprzęgiem. Jechał na koniu z przedniej pary. Kiedyś u zamożnej szlachty był to również konny pachołek z trąbką (w nocy ze światłem) poprzedzający karetę w celu zbadania drogi.  Tu widać go na przedzie zaprzęgu ubranego  tak samo jak stangret i lokaje z tyłu.",
        "Dwóch laufrów czyli służących, którzy biegli przed orszakiem lub powozem pana i oświetlali lub torowali mu drogę. Są oni ubrani wg. tzw. mody hiszpańskiej, maja na sobie krótkie do pół uda stroje wierzchnie w kolorze musztardowym, bogato zdobione srebrnymi galonami, do tego wąskie spodnie do kolan w kolorze czerwonym po bokach obszyte złotymi guzikami. Na nogach białe pończochy i czarne pantofle z klamrami. Na głowach specjalne kaszkiety zdobione strusimi piórami i zazwyczaj herbem pańskim, które nigdy nie były zdejmowane. ",
        "Widzimy tu szlachcica w stroju polskim i duchownego, którzy z uwagą przypatrują się magnackiemu zaprzęgowi. Szlachcic ubrany jest w brązowy kontusz i zielony żupan. Kontusz ma krój typowy dla tego typu ubiorów przed 1778, kiedy to wprowadzono mundury wojewódzkie i zmienił się  fason kołnierza przy kontuszu na stojący. Tu mamy kontusz jeszcze z  wąskim, szalowym kołnierzem i odrzuconymi wylotami (zwane też łapciami) –czyli rozciętymi rękawami a przepasany jest on pasiastym pasem kontuszowym. W wycięciu kontusza widać zielony żupan  a spod niego wąski rąbek białej koszuli.  Z boku widać szablę czyli karabelę i czapkę kołpak obszytą barankiem. W oczy rzuca się charakterystyczna szlachecka fryzura- tzw. czupryna, podgolony łeb, łaszczówka a nawet cebulowa głowa-czyli włosy podgolone mniej więcej na równej długości na karku i nad uszami a na czubku pozostawiona charakterystyczna kępa włosów. Do tego czarne buty z cholewami. Przedstawiony  duchowny-prezentuje tu typ tzw. księdza salonowego, który nad sutannę  przedkładał czarny strój skrojony wg. najświeższej mody ( w tym okresie w żurnalach mody pojawiały się również propozycje modnych strojów dla duchownych) w tym wypadku francuskiej. Do tego stroju nosi befkę- czyli rodzaj krawata, obecnie noszoną przez duchownych luterańskich lub kalwińskich, na nogach czarne pończochy i pantofle z modną klamrą (miała ona optycznie zmniejszać stopę, ideałem w tym okresie była mała stópka także i u panów) a na głowie pudrowaną fryzurę lub perukę w stylu francuskim tzw. gołębie  skrzydła czyli włosy na skroniach ułożone w loki a reszta zapewne zebrana w kucyk i przewiązana czarną wstążką. Pod pachą kapelusz tricorne. W tym okresie tego typu kapelusze bardzo często były właśnie tak noszone a nie na upudrowanej głowie, żeby nie pobrudzić i nie poplamić ich ciężkim pudrem robionym z mąki lub skrobi ryżowej."
    };

    private string[] headers4 = { };

    private string[] messages4 = { };

    private string[] exHeaders4 = 
    {
        "Kościół Bernardynek (obecnie nieistniejący)",
        "Budynki obok kościoła Bernardynek (ewentualnie)",
        "Dzwonnica Kościoła św. Anny",
        "Kolumna  króla  Zygmunta  III",
        "Pałac Branickich",
        "Kościół Kapucynów",
        "Południowe skrzydło Zamku Królewskiego",
        "Południowe skrzydło Zamku Królewskiego"
    };

    private string[] exMessages4 = 
    {
        "Bernardynki zadomowiły się w Warszawie w 1522 roku, ale dopiero w 1609 roku, z inicjatywy króla Zygmunta III rozpoczęto dla nich budowę kościoła. Jego twórcą był starszy budowniczy królewski, Mikołaj Duchnowski. Budowa trwała 8 lat, gmach ukończono i poświęcono w roku 1617. W ten sposób pomiędzy Zamkiem a kościołem św. Anny stanął kościół w stylu gotycko-renesansowym. Widoczne na obrazie prezbiterium ma ostrołukowe okna i szkarpy. Prace nad sąsiednimi budynkami klasztornymi trwały znacznie dłużej i ukończono je dopiero w roku 1634. Kościół miał  wysoką dzwonnicę oraz ogrody położone na skarpie od strony Wisły. Całe założenie otoczone było murem. Bernardynki były najstarszym żeńskim zakonem w Warszawie. Prowadziły szkołę dla panien szlacheckich, opiekowały się sierotami i wdowami. W 1818 roku klasztor został zamknięty, a Bernardynki przeniesiono do Przasnysza. Budynki zostały przeznaczone na wojskowe magazyny, a następnie Konserwatorium Muzyczne i Szkołę Główną Muzyki. Kościół służył jako sala koncertowa. W latach 1826-1829 u Józefa Elsnera pobierał tu lekcje kompozycji Fryderyk Chopin. Studenci szkoły muzycznej słuchali wykładów teoretycznych w budynkach Uniwersytetu Warszawskiego, natomiast na praktyki przychodzili do dawnego klasztoru, aby nie przeszkadzać profesorom innych wydziałów głośnymi ćwiczeniami i próbami. Po powstaniu listopadowym klasztor znów przejęło wojsko. Ostatecznie w latach 1843-1844 budynki rozebrano. Decyzję o likwidacji podjęto w związku z budową ulicy Nowy Zjazd i wiaduktu Pancera, które połączyły plac Zamkowy z mostem przez Wisłę. Najpierw był to most drewniany, ustawiony na łodziach u wylotu ulicy Bednarskiej, a od lat 60. XIX wieku pierwszy w Warszawie most stalowy, zwany mostem Kierbedzia. Dziś w miejscu kościoła i klasztoru znajduje się wylot tunelu trasy WZ.",
        "Nowe zabudowania klasztorne wznoszone dla sióstr bernardynek z prowizorycznym dachem. Od ulicy Grodzkiej oddziela je drewniany płot. ",
        "W latach 1578-1584 obok kościoła św. Anny została wybudowana wolnostojąca dzwonnica ufundowana przez królową Annę Jagiellonkę. Zbudowano ją na planie kwadratu z nieotynkowanej czerwonej cegły i nakryto dachem namiotowym z dachówki. Jej wzniesienie wynikało bardziej ze względów militarnych niż religijnych, ponieważ kościół miał już dzwony. Nowa wieża miała być dogodnym punktem obserwacyjnym usytuowanym przed fortyfikacjami Zamku Królewskiego. W późniejszych czasach połączono ją z kościołem murem z arkadowymi przejściami, a w latach 1819-1821 roku podwyższono i przebudowano w stylu neorenesansowym. Dzwonnica została otynkowana i zwieńczona glorietą.",
        "Kolumna Zygmunta jest najstarszym świeckim pomnikiem w Polsce oraz pierwszą w nowożytnej Europie kolumną, wzniesioną ku czci osoby świeckiej. Kolumna powstała w 1644 roku na zlecenie Władysława IV, syna Zygmunta III. Projekt pomnika jest dziełem architektów Augustyna Locciego i Constantina Tencalli, rzeźba - Clemente Mollego. Kolumna z cokołem mierzy 20 metrów, rzeźba wykonana z brązu – to kolejne 275 cm. Król  został przedstawiony w rycerskiej zbroi, z szablą w jednym i z krzyżem w drugim ręku. Przesąd ludowy głosi, że opuszczenie szabli przez króla wróży nieszczęście i upadek miasta. Na  cokole umieszczono cztery tablice w  języku  łacińskim  sławiące cnoty  i  czyny króla, obrońcy wiary i ojczyzny.  Ciekawostką jest, że figura króla była pierwotnie złocona. Pomnik wzbudził protesty nuncjusza papieskiego, ponieważ tego rodzaju wywyższenie na kolumnie było dotąd zarezerwowane dla Matki Boskiej, Chrystusa i świętych. Kolumna miała być pierwszym elementem tzw. Forum Wazów - miejsca parad i uroczystości, gloryfikującego tę dynastię. Prócz kolumny miał się tu znaleźć również pomnik Władysława IV i łuk tryumfalny Jana Kazimierza. Realizacja Forum nie doszła do skutku z powodu najazdu szwedzkiego w 1655 roku. Obecny trzon kolumny jest trzecim z rzędu. Pierwszy zdemontowano podczas remontu w końcu XIX wieku, natomiast drugi został zniszczony przez Niemców podczas powstania warszawskiego.  Po ponownym ustawieniu kolumny w 1949 roku oba historyczne trzony zostały wyeksponowane na trawniku przy południowej ścianie Zamku Królewskiego.",
        "W latach 1750-1754 w prace budowlane przy pałacu Branickich zaangażowany był architekt Jakub Fontana, który wzniósł oficyny gospodarcze od ulicy Podwale Od tej samej strony na osi głównej pałacu postawiono wówczas trójprzelotową bramę z bogatą dekoracją architektoniczną. Po śmierci właściciela pałacu, hetmana wielkiego koronnego, Jana Klemensa Branickiego, mieszkała w nim jego małżonka, Izabella z Poniatowskich, siostra króla Stanisława Augusta.",
        "W kościele Kapucynów przy ulicy Miodowej miejsce wiecznego spoczynku znalazła część śmiertelnych szczątków dwóch polskich królów – Jana III Sobieskiego (fundatora kościoła) oraz Augusta II Mocnego. Króla Jana III reprezentuje zamknięte w ołowianej skrzynce serce, Augusta II upamiętniają - zamknięte w urnie marmurowej  wnętrzności. Szczątki znajdują się w Kaplicy Królewskiej. Obecnie kościół Kapucynów słynie ze swojej ruchomej szopki. Po raz pierwszy została ona ustawiona w krypcie kościoła w 1948 roku. Skonstruowali ją  dwaj bracia kapucyni: Piusa Janowski i Konrad Wyczawski. Jej działanie opiera się na złożonym systemie pasów, kół i przekładni napędzanych jednym silnikiem elektrycznym. Od czasu swego uruchomienia szopka działa nieprzerwanie każdego roku w czasie Bożego Narodzenia. Często pojawiają się w niej postaci z historii i współczesności Kościoła, Warszawy i Polski (np. papież Jan Paweł II, papież Franciszek, Jerzy Popiełuszko, Jan III Sobieski, marszałek Piłsudski).",
        "Canaletto namalował swój obraz po pożarze południowego skrzydła Zamku, który strawił południową część budynku w marcu 1767 roku. Z prawej strony obrazu widoczny jest tylko  fragment tego skrzydła – mniej zniszczony. Prace budowlane, mające na celu wzniesienie nowego królewskiego apartamentu mieszkalnego, ruszyły w tym samym roku pod kierunkiem Jakuba Fontany. W związku z budową widać leżące przy ulicy  kamienne detale architektoniczne (kapitele, woluty, gzymsy) wykute na placu budowy przez kamieniarzy. W latach 70. XVIII wieku na końcu tego skrzydła, przy kaplicy, powstała sala, w której zawisły 22 weduty Warszawy pędzla Canaletta zamówione przez Stanisława Augusta.",
        "W XVIII wieku nie było jeszcze placu Zamkowego. Kolumna Zygmunta została wzniesiona na niewielkim placyku przed Bramą Krakowską prowadzącą od Starej Warszawy na dziedziniec przedni Zamku Królewskiego. Przez wieki brama obrosła zabudowaniami gospodarczymi Zamku i kamienicami. W jednej z nich mieściła się apteka królewska. Rozbiórka bramy wraz z otaczającymi ją zabudowaniami w latach 1818–1821 umożliwiła utworzenie placu Zamkowego zaprojektowanego przez Jakuba Kubickiego. Śladem tego miejsca jest zrekonstruowany w 1983 roku gotycki most, który w średniowieczu prowadził do Bramy Krakowskiej."
    };

    public void GetNewMessage(int sceneNumber)
    {
        switch(sceneNumber){
            case 0: 
                ModalManager.instance.ShowModal(headers0[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr], messages0[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr]);
                break;
            case 1:
                ModalManager.instance.ShowModal(headers1[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr], messages1[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr]);
                break;
            case 2:
                ModalManager.instance.ShowModal(headers2[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr], messages2[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr]);
                break;
            case 3:
                ModalManager.instance.ShowModal(headers3[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr], messages3[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr]);
                break;
            case 4:
                ModalManager.instance.ShowModal(headers4[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr], messages4[GameObject.Find("PointOfInterest").GetComponent<Interactions>().objectnr]);
                break;
        }
    }

    public void GetNewMessageExplore(int goNumber, int sceneNumber)
    {
        switch (sceneNumber)
        {
            case 0:
                ModalManager.instance.ShowModal(exHeaders0[goNumber], exMessages0[goNumber]);
                break;
            case 1:
                ModalManager.instance.ShowModal(exHeaders1[goNumber], exMessages1[goNumber]);
                break;
            case 2:
                ModalManager.instance.ShowModal(exHeaders2[goNumber], exMessages2[goNumber]);
                break;
            case 3:
                ModalManager.instance.ShowModal(exHeaders3[goNumber], exMessages3[goNumber]);
                break;
            case 4:
                ModalManager.instance.ShowModal(exHeaders4[goNumber], exMessages4[goNumber]);
                break;
        }
    }

}
